version: '3'

services:
  BEIA:
    image: hungwap375/mystore:BEIA_P
    network_mode: 'nginx-proxy'
    container_name: BEIA_P
    ports:
      - '4175:4175'
    environment:
      - VIRTUAL_HOST=api.iaproject.chuhung.com
      - VIRTUAL_PORT=4175
      - LETSENCRYPT_HOST=api.iaproject.chuhung.com

  FEIA:
    image: hungwap375/mystore:FEIA_P
    network_mode: 'nginx-proxy'
    container_name: FEIA_P
    ports:
      - '4174:4174'
    environment:
      - VIRTUAL_HOST=iaproject.chuhung.com
      - VIRTUAL_PORT=4174
      - LETSENCRYPT_HOST=iaproject.chuhung.com
